Marek Mail System: MarekMailSystem2.EmailSender Class Reference
MarekMailSystem2.EmailSender
MarekMailSystem2.EmailSender Class Reference
Public Member Functions
EmailStatus Send (string to, string subject, string body)
Sends an email with provided properties. The 'From' address is read from the configuration file. (Use the overloaded version of this method, to set the 'From' address by hand.).
EmailStatus Send (string from, string to, string subject, string body)
Sends an email with provided properties.
abstract void Send (Email email)
EmailStatus SendTemplate (string to, string subject, string body, Dictionary< string, string > context)
Replaces variables in email fields like $FOO by context["FOO"], and then sends an email. The 'From' address is read from the configuration file. (Use the overloaded version of this method, to set the 'From' address by hand.).
EmailStatus SendTemplate (string from, string to, string subject, string body, Dictionary< string, string > context)
Replaces variables in email fields like $FOO by context["FOO"], and then sends an email.
void SendTemplate (Email template, Dictionary< string, string > context)
Replaces variables in email like $FOO by context["FOO"], and then sends an email.
Detailed Description
Definition at line 7 of file EmailSender.cs.
Member Function Documentation
EmailStatus MarekMailSystem2.EmailSender.Send (string to, string subject, string body)
Sends an email with provided properties. The 'From' address is read from the configuration file. (Use the overloaded version of this method, to set the 'From' address by hand.).
Definition at line 15 of file EmailSender.cs.
References MarekMailSystem2.Email.SendingStatus.
Referenced by MarekMailSystem2.EmailSender.Send(), and MarekMailSystem2.EmailSender.SendTemplate().
EmailStatus MarekMailSystem2.EmailSender.Send (string from, string to, string subject, string body)
Sends an email with provided properties.
Definition at line 25 of file EmailSender.cs.
References MarekMailSystem2.EmailSender.Send(), and MarekMailSystem2.Email.SendingStatus.
abstract void MarekMailSystem2.EmailSender.Send (Email email) [pure virtual]
Implements MarekMailSystem2.IEmailSender.
Implemented in MarekMailSystem2.EmailManager, and MarekMailSystem2.SmtpEmailSender.
EmailStatus MarekMailSystem2.EmailSender.SendTemplate (string to, string subject, string body, Dictionary< string, string > context)
Replaces variables in email fields like $FOO by context["FOO"], and then sends an email. The 'From' address is read from the configuration file. (Use the overloaded version of this method, to set the 'From' address by hand.).
Definition at line 39 of file EmailSender.cs.
References MarekMailSystem2.Email.SendingStatus.
Referenced by MarekMailSystem2.EmailManager.SendSavedTemplate(), and MarekMailSystem2.EmailSender.SendTemplate().
EmailStatus MarekMailSystem2.EmailSender.SendTemplate (string from, string to, string subject, string body, Dictionary< string, string > context)
Replaces variables in email fields like $FOO by context["FOO"], and then sends an email.
Definition at line 50 of file EmailSender.cs.
References MarekMailSystem2.Email.SendingStatus, and MarekMailSystem2.EmailSender.SendTemplate().
void MarekMailSystem2.EmailSender.SendTemplate (Email template, Dictionary< string, string > context)
Replaces variables in email like $FOO by context["FOO"], and then sends an email.
Parameters:
template Template email to be send.
context A dictionary with variables values.
Definition at line 63 of file EmailSender.cs.
References MarekMailSystem2.EmailSender.Send().
The documentation for this class was generated from the following file:
tmp/test-doxy-mms/MarekMailSystem/MarekMailSystem2/EmailSender.cs