Marek Mail System: MarekMailSystem2Tests.NormalTests Class Reference
MarekMailSystem2Tests.NormalTests
MarekMailSystem2Tests.NormalTests Class Reference
test fixture blabla
Public Member Functions
void Init ()
setup bla bla
void EmailManagerTest1 ()
test email manager test 1 blabla
void EmailManagerTest2 ()
void EmailManagerTemplateTest1 ()
Simple template test.
void EmailManagerTemplateTest2 ()
void EmailManagerTemplateTest3 ()
void SmtpEmailSenderTest1 ()
void SmtpEmailSenderTest2 ()
void EmailAltViewTest1 ()
void EmailTemplateTest1 ()
void EmailTemplateTest2 ()
void StupidTests ()
This test don't tests anything important.
Private Attributes
Dictionary< string, string > context
List< string > receivers
List< string > names
string template
Detailed Description
test fixture blabla
Definition at line 14 of file NormalTests.cs.
Member Function Documentation
void MarekMailSystem2Tests.NormalTests.Init ()
setup bla bla
Definition at line 32 of file NormalTests.cs.
References MarekMailSystem2Tests.NormalTests.context, MarekMailSystem2Tests.NormalTests.names, and MarekMailSystem2Tests.NormalTests.receivers.
Referenced by MarekMailSystem2Tests.Go.Main().
void MarekMailSystem2Tests.NormalTests.EmailManagerTest1 ()
test email manager test 1 blabla
Definition at line 65 of file NormalTests.cs.
References MarekMailSystem2.EmailManager.Send(), and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.EmailManagerTest2 ()
Definition at line 78 of file NormalTests.cs.
References MarekMailSystem2.EmailManager.Send(), and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest1 ()
Simple template test.
Definition at line 93 of file NormalTests.cs.
References MarekMailSystem2Tests.NormalTests.context, MarekMailSystem2.EmailManager.SendSavedTemplate(), and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest2 ()
Definition at line 110 of file NormalTests.cs.
References MarekMailSystem2Tests.NormalTests.context, MarekMailSystem2Tests.NormalTests.receivers, MarekMailSystem2.EmailManager.SendSavedTemplate(), and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest3 ()
Definition at line 123 of file NormalTests.cs.
References MarekMailSystem2Tests.NormalTests.context, MarekMailSystem2Tests.NormalTests.names, MarekMailSystem2Tests.NormalTests.receivers, MarekMailSystem2.EmailManager.SendSavedTemplate(), and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.SmtpEmailSenderTest1 ()
Definition at line 137 of file NormalTests.cs.
References MarekMailSystem2.SmtpEmailSender.Send(), MarekMailSystem2.Email.SendingStatus, and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.SmtpEmailSenderTest2 ()
Definition at line 153 of file NormalTests.cs.
References MarekMailSystem2.SmtpEmailSender.Host, MarekMailSystem2.SmtpEmailSender.Password, MarekMailSystem2.SmtpEmailSender.Port, MarekMailSystem2.SmtpEmailSender.Send(), MarekMailSystem2.Email.SendingStatus, MarekMailSystem2.SmtpEmailSender.Ssl, MarekMailSystem2.EmailStatus.Status, and MarekMailSystem2.SmtpEmailSender.UserName.
void MarekMailSystem2Tests.NormalTests.EmailAltViewTest1 ()
Definition at line 176 of file NormalTests.cs.
References MarekMailSystem2.Email.AltView, MarekMailSystem2.Email.Body, MarekMailSystem2.Email.IsBodyHtml, MarekMailSystem2.SmtpEmailSender.Send(), MarekMailSystem2.Email.SendingStatus, and MarekMailSystem2.EmailStatus.Status.
void MarekMailSystem2Tests.NormalTests.EmailTemplateTest1 ()
Definition at line 209 of file NormalTests.cs.
References MarekMailSystem2Tests.NormalTests.context, and MarekMailSystem2.Email.ProcessTemplate().
Referenced by MarekMailSystem2Tests.Go.Main().
void MarekMailSystem2Tests.NormalTests.EmailTemplateTest2 ()
Definition at line 218 of file NormalTests.cs.
References MarekMailSystem2Tests.NormalTests.context, MarekMailSystem2.Email.ProcessTemplate(), MarekMailSystem2Tests.NormalTests.receivers, and MarekMailSystem2.SmtpEmailSender.Send().
void MarekMailSystem2Tests.NormalTests.StupidTests ()
This test don't tests anything important.
Definition at line 233 of file NormalTests.cs.
Member Data Documentation
Dictionary<string, string> MarekMailSystem2Tests.NormalTests.context [private]
Definition at line 17 of file NormalTests.cs.
Referenced by MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest1(), MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest2(), MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest3(), MarekMailSystem2Tests.NormalTests.EmailTemplateTest1(), MarekMailSystem2Tests.NormalTests.EmailTemplateTest2(), and MarekMailSystem2Tests.NormalTests.Init().
List<string> MarekMailSystem2Tests.NormalTests.receivers [private]
Definition at line 18 of file NormalTests.cs.
Referenced by MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest2(), MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest3(), MarekMailSystem2Tests.NormalTests.EmailTemplateTest2(), and MarekMailSystem2Tests.NormalTests.Init().
List<string> MarekMailSystem2Tests.NormalTests.names [private]
Definition at line 19 of file NormalTests.cs.
Referenced by MarekMailSystem2Tests.NormalTests.EmailManagerTemplateTest3(), and MarekMailSystem2Tests.NormalTests.Init().
string MarekMailSystem2Tests.NormalTests.template [private]
Initial value:
            "Top secret message to: $SURNAME $NAME\n" +
            "$HEADER $NAME !\n" +
            "blablabla $NOTUSED blebleble\n" +
            "blublu blu\n" +
            "     $FOOT !\n" +
            "     Date: $DATE"
Definition at line 20 of file NormalTests.cs.
The documentation for this class was generated from the following file:
tmp/test-doxy-mms/MarekMailSystem/MarekMailSystem2Tests/NormalTests.cs